CREATE TABLE IF NOT EXISTS BRAND(
	B_ID INT AUTO_INCREMENT,
	B_NAME VARCHAR(100),
	B_IMAGE VARCHAR(10),

	CONSTRAINT PK_B_ID PRIMARY KEY(B_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
	P_ID INT AUTO_INCREMENT,
	P_NAME VARCHAR(300),
	P_PRICE INT,
	P_STATUS BOOLEAN,
	P_BRAND INT,
	P_DESC VARCHAR(100),
	P_IMAGE VARCHAR(10),
	CREATED_AT VARCHAR(11),

	CONSTRAINT PK_P_ID PRIMARY KEY(P_ID),
	CONSTRAINT FK_P_BRAND FOREIGN KEY(P_BRAND) REFERENCES BRAND(B_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    U_ID INT AUTO_INCREMENT,
    U_FIRST_NAME VARCHAR(100),
    U_LAST_NAME VARCHAR(100),
    U_EMAIL VARCHAR(100),
	U_PASSWORD VARCHAR(255),
	U_PROFILE VARCHAR(10),

	CONSTRAINT PK_U_ID PRIMARY KEY(U_ID)
);